[package]
name = "weechat-matrix"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "ISC"

[lib]
name = "matrix"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.68"
url = "2.1.1"
tokio = { version = "0.2.13", features = [ "rt-threaded" ] }
async-std = { version = "1.5.0", features = [ "unstable" ] }
clap = "2.33.0"
async-trait = "0.1.29"
uuid = { version = "0.8.1", features = ["v4"] }

weechat = { git = "https://github.com/poljar/rust-weechat", branch = "master", features = ["async-executor"] }
weechat-sys = { git = "https://github.com/poljar/rust-weechat", branch = "master" }

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk/"
branch = "master"
default-features = false
features = ["encryption", "sqlite-cryptostore"]
